# Generated by Django 5.2.13 on 2026-04-08 05:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('dob', models.DateField()),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('campus', models.CharField(db_index=True, max_length=255)),
                ('budget_min', models.PositiveIntegerField(default=0)),
                ('budget_max', models.PositiveIntegerField(default=0)),
                ('smoking_preference', models.CharField(choices=[('YES', 'Smoker'), ('NO', 'Non-Smoker'), ('OCC', 'Occasional')], default='NO', max_length=3)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NON_BINARY', 'Non-Binary'), ('OTHER', 'Other'), ('PREFER_NOT_SAY', 'Prefer not to say')], default='PREFER_NOT_SAY', max_length=20)),
                ('drinking_preference', models.CharField(choices=[('NEVER', 'Never'), ('SOCIALLY', 'Socially'), ('REGULARLY', 'Regularly')], default='SOCIALLY', max_length=20)),
                ('sleep_schedule', models.CharField(choices=[('EARLY_BIRD', 'Early Bird (Before 10 PM)'), ('NIGHT_OWL', 'Night Owl (After 12 AM)'), ('FLEXIBLE', 'Flexible / In-between')], default='FLEXIBLE', max_length=20)),
                ('gender_preference', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NON_BINARY', 'Non-Binary'), ('OTHER', 'Other'), ('PREFER_NOT_SAY', 'Prefer not to say'), ('ANY', 'No Preference')], default='ANY', max_length=20)),
            ],
        ),
    ]
