# Generated by Django 5.2.14 on 2026-05-06 14:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_listing_conversation_houselisting_listingrequest_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoveoutItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FURNITURE", "Furniture"),
                            ("ELECTRONICS", "Electronics"),
                            ("TEXTBOOKS", "Textbooks"),
                            ("APPLIANCES", "Appliances"),
                            ("OTHER", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("GOOD", "Good"),
                            ("FAIR", "Fair"),
                            ("USED", "Used"),
                            ("DAMAGED", "Damaged"),
                        ],
                        max_length=16,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("contact_email", models.EmailField(max_length=254)),
                ("image_data", models.BinaryField(blank=True, null=True)),
                ("image_filename", models.CharField(blank=True, max_length=255)),
                ("image_content_type", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moveout_items",
                        to="app.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
