# Generated by Django 5.2.14 on 2026-05-07 03:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_moveoutitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomVacancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('housing_type', models.CharField(choices=[('APARTMENT', 'Apartment'), ('HOUSE', 'House'), ('STUDIO', 'Studio'), ('DORM', 'Dorm / Campus Housing'), ('OTHER', 'Other')], max_length=32)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_from', models.DateField()),
                ('lease_duration', models.CharField(choices=[('MONTH_TO_MONTH', 'Month to Month'), ('3_MONTHS', '3 Months'), ('6_MONTHS', '6 Months'), ('12_MONTHS', '12 Months'), ('12_PLUS', '12+ Months')], max_length=20)),
                ('total_rooms', models.PositiveIntegerField()),
                ('gender_preference', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NON_BINARY', 'Non-Binary'), ('OTHER', 'Other'), ('PREFER_NOT_SAY', 'Prefer not to say'), ('ANY', 'No Preference')], default='ANY', max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('image_data', models.BinaryField(blank=True, null=True)),
                ('image_filename', models.CharField(blank=True, max_length=255)),
                ('image_content_type', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_vacancies', to='app.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
